//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose PoseLeft
        {
            get
            {
                return SteamVR_Actions.default_PoseLeft;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Pose PoseRight
        {
            get
            {
                return SteamVR_Actions.default_PoseRight;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.default_Move;
            }
        }
        
        public virtual SteamVR_Action_Vector2 SmoothTurn
        {
            get
            {
                return SteamVR_Actions.default_SmoothTurn;
            }
        }
        
        public virtual SteamVR_Action_Boolean Sprint
        {
            get
            {
                return SteamVR_Actions.default_Sprint;
            }
        }
        
        public virtual SteamVR_Action_Boolean Interact
        {
            get
            {
                return SteamVR_Actions.default_Interact;
            }
        }
        
        public virtual SteamVR_Action_Boolean TechTree
        {
            get
            {
                return SteamVR_Actions.default_TechTree;
            }
        }
        
        public virtual SteamVR_Action_Boolean Inventory
        {
            get
            {
                return SteamVR_Actions.default_Inventory;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jump
        {
            get
            {
                return SteamVR_Actions.default_Jump;
            }
        }
        
        public virtual SteamVR_Action_Boolean TakeAll
        {
            get
            {
                return SteamVR_Actions.default_TakeAll;
            }
        }
        
        public virtual SteamVR_Action_Boolean RotateBuildingLeft
        {
            get
            {
                return SteamVR_Actions.default_RotateBuildingLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean RotoateBuildingRight
        {
            get
            {
                return SteamVR_Actions.default_RotoateBuildingRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean CycleHotbarLeft
        {
            get
            {
                return SteamVR_Actions.default_CycleHotbarLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean CycleHotbarRight
        {
            get
            {
                return SteamVR_Actions.default_CycleHotbarRight;
            }
        }
        
        public virtual SteamVR_Action_Vector2 MenuJoystickSecondary
        {
            get
            {
                return SteamVR_Actions.default_MenuJoystickSecondary;
            }
        }
        
        public virtual SteamVR_Action_Vector2 MenuJoystickPrimary
        {
            get
            {
                return SteamVR_Actions.default_MenuJoystickPrimary;
            }
        }
        
        public virtual SteamVR_Action_Boolean Craft
        {
            get
            {
                return SteamVR_Actions.default_Craft;
            }
        }
        
        public virtual SteamVR_Action_Boolean CraftFive
        {
            get
            {
                return SteamVR_Actions.default_CraftFive;
            }
        }
        
        public virtual SteamVR_Action_Boolean CraftAll
        {
            get
            {
                return SteamVR_Actions.default_CraftAll;
            }
        }
        
        public virtual SteamVR_Action_Boolean Transfer
        {
            get
            {
                return SteamVR_Actions.default_Transfer;
            }
        }
        
        public virtual SteamVR_Action_Boolean TransferHalf
        {
            get
            {
                return SteamVR_Actions.default_TransferHalf;
            }
        }
        
        public virtual SteamVR_Action_Boolean TransferAll
        {
            get
            {
                return SteamVR_Actions.default_TransferAll;
            }
        }
        
        public virtual SteamVR_Action_Boolean UIPageLeft
        {
            get
            {
                return SteamVR_Actions.default_UIPageLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean UIPageRight
        {
            get
            {
                return SteamVR_Actions.default_UIPageRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean UIPageRightSecondary
        {
            get
            {
                return SteamVR_Actions.default_UIPageRightSecondary;
            }
        }
        
        public virtual SteamVR_Action_Boolean UIPageLeftSecondary
        {
            get
            {
                return SteamVR_Actions.default_UIPageLeftSecondary;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleMenu
        {
            get
            {
                return SteamVR_Actions.default_ToggleMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean UISubmit
        {
            get
            {
                return SteamVR_Actions.default_UISubmit;
            }
        }
        
        public virtual SteamVR_Action_Boolean UICancel
        {
            get
            {
                return SteamVR_Actions.default_UICancel;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleErase
        {
            get
            {
                return SteamVR_Actions.default_ToggleErase;
            }
        }
        
        public virtual SteamVR_Action_Boolean Use
        {
            get
            {
                return SteamVR_Actions.default_Use;
            }
        }
        
        public virtual SteamVR_Action_Boolean UIShortcut2
        {
            get
            {
                return SteamVR_Actions.default_UIShortcut2;
            }
        }
        
        public virtual SteamVR_Action_Boolean UIShortcut1
        {
            get
            {
                return SteamVR_Actions.default_UIShortcut1;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleHotbarEdit
        {
            get
            {
                return SteamVR_Actions.default_ToggleHotbarEdit;
            }
        }
        
        public virtual SteamVR_Action_Boolean ExitHotbarEdit
        {
            get
            {
                return SteamVR_Actions.default_ExitHotbarEdit;
            }
        }
        
        public virtual SteamVR_Action_Boolean PauseMenu
        {
            get
            {
                return SteamVR_Actions.default_PauseMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean ClearHotbar
        {
            get
            {
                return SteamVR_Actions.default_ClearHotbar;
            }
        }
        
        public virtual SteamVR_Action_Boolean HotbarSwap
        {
            get
            {
                return SteamVR_Actions.default_HotbarSwap;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
