//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_default p__default;
        
        private static SteamVR_Input_ActionSet_UI p_UI;
        
        private static SteamVR_Input_ActionSet_IK p_IK;
        
        public static SteamVR_Input_ActionSet_default _default
        {
            get
            {
                return SteamVR_Actions.p__default.GetCopy<SteamVR_Input_ActionSet_default>();
            }
        }
        
        public static SteamVR_Input_ActionSet_UI UI
        {
            get
            {
                return SteamVR_Actions.p_UI.GetCopy<SteamVR_Input_ActionSet_UI>();
            }
        }
        
        public static SteamVR_Input_ActionSet_IK IK
        {
            get
            {
                return SteamVR_Actions.p_IK.GetCopy<SteamVR_Input_ActionSet_IK>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p__default = ((SteamVR_Input_ActionSet_default)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_default>("/actions/default")));
            SteamVR_Actions.p_UI = ((SteamVR_Input_ActionSet_UI)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_UI>("/actions/UI")));
            SteamVR_Actions.p_IK = ((SteamVR_Input_ActionSet_IK)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_IK>("/actions/IK")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions._default,
                    SteamVR_Actions.UI,
                    SteamVR_Actions.IK};
        }
    }
}
