# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check typos
        uses: crate-ci/typos@master
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugin

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: plugin
        path: ./plugin/bin/Release/netstandard2.1/techtonica_vr.dll

  package:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: plugin
      - name: Copy Files
        run: |
          mkdir -p ./artifact/BepInEx/plugins/techtonica_vr/assets && mkdir -p ./artifact/Techtonica_Data
          cp techtonica_vr.dll ./artifact/BepInEx/plugins
          cp -r ./libs/* ./artifact/Techtonica_Data/
          cp -r ./unity/AssetBundles/StandaloneWindows/* ./artifact/BepInEx/plugins/techtonica_vr/assets
          cp {README.adoc,CHANGELOG.md,LICENSE,manifest.json,icon.png} ./artifact/
      - name: Upload Release Asset Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-artifact
          path: artifact


