on:
    workflow_run:
      workflows: [".Net"]
      branches: ["master"]
      types:
        - completed

permissions:
    contents: write
    pull-requests: write

name: release-please

jobs:
    release-please:
      runs-on: ubuntu-latest
      steps:
        - id: release
          uses: google-github-actions/release-please-action@v4
          with:
            token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
            config-file: release-please-config.json
        - name: Download release artifact
          if: ${{ steps.release.outputs.release_created }}
          uses: dawidd6/action-download-artifact@v3
          with:
            workflow: "dotnet.yml"
            name: release-artifact
            skip_unpack: true
        - name: Download Tobey.UnityAudio
          if: ${{ steps.release.outputs.release_created }}
          uses: dsaltares/fetch-gh-release-asset@1.1.1
          with:
            repo: "toebeann/Tobey.UnityAudio"
            file: "Tobey.UnityAudio.zip"
            version: "tags/v2.0.2"
            token: ${{ secrets.DEPENDENCY_TOKEN }}
        - name: Zip release artifact
          if: ${{ steps.release.outputs.release_created }}
          run: |
            mkdir artifact
            unzip release-artifact.zip -d ./artifact/
            cd artifact && npx downdoc README.adoc && zip -r techtonica_vr-${{ steps.release.outputs.tag_name }}-thunderstore.zip ./ && cd ..
            mv artifact/techtonica_vr-${{ steps.release.outputs.tag_name }}-thunderstore.zip .
            rm artifact/README.md
            unzip Tobey.UnityAudio.zip -d ./artifact/
            cd artifact && zip -r techtonica_vr-${{ steps.release.outputs.tag_name }}.zip ./ && cd ..
            mv artifact/techtonica_vr-${{ steps.release.outputs.tag_name }}.zip .
        - name: Upload release artifact
          if: ${{ steps.release.outputs.release_created }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            gh release upload ${{ steps.release.outputs.tag_name }} techtonica_vr-${{ steps.release.outputs.tag_name }}.zip --repo Xenira/TechtonicaVR
        - name: Upload to Thunderstore
          uses: GreenTF/upload-thunderstore-package@v4.3
          if: ${{ steps.release.outputs.release_created }}
          with:
            namespace: "3_141"
            community: techtonica
            name: TechtonicaVR
            description: VR mod for Techtonica
            categories: |
              mods
            file: techtonica_vr-${{ steps.release.outputs.tag_name }}-thunderstore.zip
            version: "${{ steps.release.outputs.major }}.${{ steps.release.outputs.major }}.${{ steps.release.outputs.patch }}"
            repo: thunderstore.io
            token: ${{ secrets.THUNDERSTORE_KEY }}
